/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;

/**
 *
 * @author Larry
 */
public class calculator extends javax.swing.JFrame {

    double firstnum;
    double secondnum;
    double result;
    String operations;
    
    
    public calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calculatorDispaly = new javax.swing.JTextField();
        calculator1 = new javax.swing.JButton();
        calculator2 = new javax.swing.JButton();
        calculator3 = new javax.swing.JButton();
        calculator4 = new javax.swing.JButton();
        calculator5 = new javax.swing.JButton();
        calculator6 = new javax.swing.JButton();
        calculator7 = new javax.swing.JButton();
        calculator8 = new javax.swing.JButton();
        calculator15 = new javax.swing.JButton();
        calculator16 = new javax.swing.JButton();
        calculator9 = new javax.swing.JButton();
        calculator10 = new javax.swing.JButton();
        calculator11 = new javax.swing.JButton();
        calculator12 = new javax.swing.JButton();
        calculator13 = new javax.swing.JButton();
        calculator14 = new javax.swing.JButton();
        calculator17 = new javax.swing.JButton();
        calculator18 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        calculatorDispaly.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        calculatorDispaly.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        calculatorDispaly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatorDispalyActionPerformed(evt);
            }
        });

        calculator1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        calculator1.setText("1");
        calculator1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculator1ActionPerformed(evt);
            }
        });

        calculator2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        calculator2.setText("2");
        calculator2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculator2ActionPerformed(evt);
            }
        });

        calculator3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        calculator3.setText("3");
        calculator3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculator3ActionPerformed(evt);
            }
        });

        calculator4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        calculator4.setText("4");
        calculator4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculator4ActionPerformed(evt);
            }
        });

        calculator5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        calculator5.setText("5");
        calculator5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculator5ActionPerformed(evt);
            }
        });

        calculator6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        calculator6.setText("6");
        calculator6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculator6ActionPerformed(evt);
            }
        });

        calculator7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        calculator7.setText("7");
        calculator7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculator7ActionPerformed(evt);
            }
        });

        calculator8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        calculator8.setText("8");
        calculator8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculator8ActionPerformed(evt);
            }
        });

        calculator15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        calculator15.setText("+/-");
        calculator15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculator15ActionPerformed(evt);
            }
        });

        calculator16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        calculator16.setText(".");
        calculator16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculator16ActionPerformed(evt);
            }
        });

        calculator9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        calculator9.setText("9");
        calculator9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculator9ActionPerformed(evt);
            }
        });

        calculator10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        calculator10.setText("0");
        calculator10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculator10ActionPerformed(evt);
            }
        });

        calculator11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        calculator11.setText("+");
        calculator11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculator11ActionPerformed(evt);
            }
        });

        calculator12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        calculator12.setText("-");
        calculator12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculator12ActionPerformed(evt);
            }
        });

        calculator13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        calculator13.setText("/");
        calculator13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculator13ActionPerformed(evt);
            }
        });

        calculator14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        calculator14.setText("*");
        calculator14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculator14ActionPerformed(evt);
            }
        });

        calculator17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        calculator17.setText("C");
        calculator17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculator17ActionPerformed(evt);
            }
        });

        calculator18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        calculator18.setText("=");
        calculator18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculator18ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(calculator17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(calculator13, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(calculator14, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calculator18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(calculatorDispaly, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(calculator1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calculator2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calculator3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calculator4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(calculator5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calculator6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calculator7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calculator8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(calculator9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(calculator10, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(calculator11, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(calculator15, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calculator16, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(calculator12, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(calculatorDispaly, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculator1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calculator2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calculator3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calculator4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculator5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calculator6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calculator7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calculator8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculator9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calculator10, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calculator11, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calculator12, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculator13, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calculator14, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calculator16, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calculator15, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(calculator17, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calculator18, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(584, 584, 584))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculator1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculator1ActionPerformed
     String Enternumber = jtxtDisplay.getText() + calculator1.getText();
    jtxtDisplay.setText(Enternumber);  
    }//GEN-LAST:event_calculator1ActionPerformed

    private void calculator2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculator2ActionPerformed
     String Enternumber = jtxtDisplay.getText() + calculator2.getText();
    jtxtDisplay.setText(Enternumber);   
    }//GEN-LAST:event_calculator2ActionPerformed

    private void calculator3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculator3ActionPerformed
     String Enternumber = jtxtDisplay.getText() + calculator3.getText();
    jtxtDisplay.setText(Enternumber);   
    }//GEN-LAST:event_calculator3ActionPerformed

    private void calculator4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculator4ActionPerformed
     String Enternumber = jtxtDisplay.getText() + calculator4.getText();
    jtxtDisplay.setText(Enternumber);   
    }//GEN-LAST:event_calculator4ActionPerformed

    private void calculator5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculator5ActionPerformed
     String Enternumber = jtxtDisplay.getText() + calculator5.getText();
    jtxtDisplay.setText(Enternumber);  
    }//GEN-LAST:event_calculator5ActionPerformed

    private void calculator6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculator6ActionPerformed
     String Enternumber = jtxtDisplay.getText() + calculator6.getText();
    jtxtDisplay.setText(Enternumber);  
    }//GEN-LAST:event_calculator6ActionPerformed

    private void calculator7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculator7ActionPerformed
     String Enternumber = jtxtDisplay.getText() + calculator7.getText();
    jtxtDisplay.setText(Enternumber);  
    }//GEN-LAST:event_calculator7ActionPerformed

    private void calculator8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculator8ActionPerformed
     String Enternumber = jtxtDisplay.getText() + calculator8.getText();
    jtxtDisplay.setText(Enternumber);   
    }//GEN-LAST:event_calculator8ActionPerformed

    private void calculator9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculator9ActionPerformed
     String Enternumber = jtxtDisplay.getText() + calculator9.getText();
    jtxtDisplay.setText(Enternumber);    
    }//GEN-LAST:event_calculator9ActionPerformed

    private void calculator10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculator10ActionPerformed
     String Enternumber = jtxtDisplay.getText() + calculator10.getText();
    jtxtDisplay.setText(Enternumber);   
    }//GEN-LAST:event_calculator10ActionPerformed

    private void calculator17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculator17ActionPerformed
     String Enternumber = jtxtDisplay.getText() + calculator17.getText();
    jtxtDisplay.setText(Enternumber);    // TODO add your handling code here:
    }//GEN-LAST:event_calculator17ActionPerformed

    private void calculator11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculator11ActionPerformed
    
        firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtextDisplay.setText("");
        operations="+";
    }//GEN-LAST:event_calculator11ActionPerformed

    private void calculator12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculator12ActionPerformed
    firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtextDisplay.setText("");
        operations="-";   
    }//GEN-LAST:event_calculator12ActionPerformed

    private void calculator13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculator13ActionPerformed
    firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtextDisplay.setText("");
        operations="/";
    }//GEN-LAST:event_calculator13ActionPerformed

    private void calculator14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculator14ActionPerformed
    firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtextDisplay.setText("");
        operations="*";
    }//GEN-LAST:event_calculator14ActionPerformed

    private void calculator15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculator15ActionPerformed
    
        double ops = Double.parseDouble(String.valueOf(calculatorDisplay.getText()));
        ops =ops * (-1);
        calculatorDisplay.setText(String.valueOf(ops));
        
    }//GEN-LAST:event_calculator15ActionPerformed

    private void calculator16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculator16ActionPerformed
    String Enternumber = jtxtDisplay.getText() + calculator16.getText();
    jtxtDisplay.setText(Enternumber);    // TODO add your handling code here:
    }//GEN-LAST:event_calculator16ActionPerformed

    private void calculatorDispalyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculatorDispalyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calculatorDispalyActionPerformed

    private void calculator18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculator18ActionPerformed
    
        String answer;
        
        secondnum = Double.parseDouble((String) calculatorDisplay.getText());
        if (operations == "+")
        {
           
            result = firstnum + secondnum;
            answer = String.format("%.of",result);
            jtxtDisplay.setText(answer);
        }
        else if (operations == "-")
        {
            result = firstnum - secondnum;
            answer = String.format("%.of",result);
            jtxtDisplay.setText(answer);
        }
        else if (operations == "*")
        {
            result = firstnum * secondnum;
            answer = String.format("%.of",result);
            jtxtDisplay.setText(answer);
        }
        else if (operations == "/")
        {
            result = firstnum / secondnum;
            answer = String.format("%.of",result);
            jtxtDisplay.setText(answer);
        }
        else if (operations == "%")
        {
            result = firstnum % secondnum;
            answer = String.format("%.of",result);
            jtxtDisplay.setText(answer);
        }
    }//GEN-LAST:event_calculator18ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculator1;
    private javax.swing.JButton calculator10;
    private javax.swing.JButton calculator11;
    private javax.swing.JButton calculator12;
    private javax.swing.JButton calculator13;
    private javax.swing.JButton calculator14;
    private javax.swing.JButton calculator15;
    private javax.swing.JButton calculator16;
    private javax.swing.JButton calculator17;
    private javax.swing.JButton calculator18;
    private javax.swing.JButton calculator2;
    private javax.swing.JButton calculator3;
    private javax.swing.JButton calculator4;
    private javax.swing.JButton calculator5;
    private javax.swing.JButton calculator6;
    private javax.swing.JButton calculator7;
    private javax.swing.JButton calculator8;
    private javax.swing.JButton calculator9;
    private javax.swing.JTextField calculatorDispaly;
    // End of variables declaration//GEN-END:variables
}
